services:
  storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data

  otel-collector:
    image: "otel/opentelemetry-collector-contrib:0.95.0"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector/config.yaml
    ports:
      - 4317:4317
      - 4318:4318

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  azurite_data:
