
POST http://localhost:7071/api/WorkflowOrc_HttpStart

{
  "name": "samplesec",
  "source": "KeyVault",
  "destination": "BlobStorage",
  "blobStorageInfo": {
    "storageAccountName": "ydinventorylogs",
    "blobName": "sec2bcreated.txt",
    "containerName": "workflows"
  }
}

###

POST http://localhost:7071/api/CopyBlobWorkflow_HttpStart

{
  "name": "sampleName",
  "source": "sourceIdentifier",
  "destination": "destinationIdentifier",
  "sourceBlobStorageInfo": {
    "storageAccountName": "ydinventorylogs",
    "blobName": "functions.csv",
    "containerName": "sourcecontainer"
  },
  "targetBlobStorageInfo": {
    "storageAccountName": "ydinventorylogs",
    "blobName": "copy_of_functions.csv",
    "containerName": "targetcontainer"
  }
}